/* eslint-disable indent */

import Agra from '../assets/brb/schedules/agra.svg';
import Test from '../assets/brb/schedules/test.jpg';


export const citiesList = [
    [{
        image: Agra,
        place: 'Dehradun',
        date: '31 AUG 2023',
        link: 'https://push.org',
        backgroundColor: '#194395',
        hasEnded: false,
    },
    {
        image: Agra,
        place: 'Kolkata',
        date: '2 Sept 2023',
        link: 'https://push.org',
        backgroundColor: '#7A3DA9',
        hasEnded: false,
    }],
    [{
        image: Test,
        place: 'Kochi',
        date: '8 Sept 2023',
        link: 'https://push.org',
        backgroundColor: '#16837C',
        hasEnded: false,
    },
    {
        image: Agra,
        place: 'Trivandrum',
        date: '15 Sept 2023',
        link: 'https://push.org',
        backgroundColor: '#DA786A',
        hasEnded: false,
    }],
    [{
        image: Agra,
        place: 'Indore',
        date: '18 Sept 2023',
        link: 'https://push.org',
        backgroundColor: '#299EC2',
        hasEnded: false,
    },
    {
        image: Test,
        place: 'Pune',
        date: '23 Sept 2023',
        link: 'https://push.org',
        backgroundColor: '#3F53AA',
        hasEnded: false,
    }],
    [{
        image: Agra,
        place: 'Ahmedabad',
        date: '30 Sept 2023',
        link: 'https://push.org',
        backgroundColor: '#194395',
        hasEnded: false,
    },
    {
        image: Test,
        place: 'Mumbai',
        date: '7 Oct 2023',
        link: 'https://push.org',
        backgroundColor: '#7A3DA9',
        hasEnded: false,
    }],
    [{
        image: Agra,
        place: 'Jaipur',
        date: '14 Oct 2023',
        link: 'https://push.org',
        backgroundColor: '#194395',
        hasEnded: false,
    },
    {
        image: Test,
        place: 'Bhopal',
        date: '16 Oct 2023',
        link: 'https://push.org',
        backgroundColor: '#16837C',
        hasEnded: false,
    }],
    [{
        image: Agra,
        place: 'Delhi ',
        date: '10 Nov 2023',
        link: 'push.org',
        backgroundColor: '#DA786A',
        hasEnded: false,
    },
    {
        image: Test,
        place: 'Kanpur',
        date: '15 Nov 2023',
        link: 'push.org',
        backgroundColor: '#299EC2',
        hasEnded: false,
    }],
    [{
        image: Agra,
        place: 'Lucknow',
        date: '17 Nov 2023',
        link: 'push.org',
        backgroundColor: '#3F53AA',
        hasEnded: false,
    },
    {
        image: Agra,
        place: 'Agra',
        date: '25 Nov 2023',
        link: 'push.org',
        backgroundColor: '#194395',
        hasEnded: false,
    }],
    [{
        image: Test,
        place: 'Coimbatore',
        date: '28 Nov 2023',
        link: 'push.org',
        backgroundColor: '#7A3DA9',
        hasEnded: false,
    },
    {
        image: Agra,
        place: 'Chennai',
        date: '1 Dec 2023',
        link: 'push.org',
        backgroundColor: '#299EC2',
        hasEnded: false,
    }],
    [{
        image: Test,
        place: 'Hyderabad',
        date: '5 Dec 2023',
        link: 'push.org',
        backgroundColor: '#DA786A',
        hasEnded: false,
    },
    {
        image: Agra,
        place: 'Bangalore',
        date: '8 Dec 2023',
        link: 'push.org',
        backgroundColor: '#299EC2',
        hasEnded: false,
    }],
];