export const brbCommPartnersList = [
  {
    srcref: 'gitcoin',
    link: 'https://twitter.com/gitcoin',
    alt: 'Gitcoin, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Gitcoin Twitter',
  },
  {
    srcref: 'ensdao',
    link: 'https://twitter.com/ENS_DAO',
    alt: 'ENS DAO, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit ENS DAO Twitter',
  },
  {
    srcref: 'learnweb3',
    link: 'https://twitter.com/LearnWeb3DAO',
    alt: 'LearnWeb3DAO, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit LearnWeb3DAO Twitter',
  },
  {
    srcref: 'buidlerstribe',
    link: 'https://buidlerstribe.com/',
    alt: 'Buidlers Tribe, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Buidlers Tribe Website',
  },
  {
    srcref: 'devfolio',
    link: 'https://devfolio.co/',
    alt: 'Devfolio, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Devfolio Website',
  },
  {
    srcref: 'hyddao',
    link: 'https://twitter.com/HyderabadDAO',
    alt: 'Hyderabad DAO, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Hyderabad DAO Website',
  },
  {
    srcref: 'indiverse',
    link: 'https://www.linkedin.com/company/indi-verse-dao/',
    alt: 'Indi Verse DAO, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Indi Verse DAO Website',
  },
  {
    srcref: 'gdsc',
    link: 'twitter.com/gdscmuj',
    alt: 'GDSC Jaipur, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit GDSC Jaipur',
  },
  {
    srcref: 'tph',
    link: 'https://twitter.com/0xTPH',
    alt: 'The Product House, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit The Product House Twiiter',
  },
  {
    srcref: 'tribeacademy',
    link: 'https://www.youtube.com/@Cryptotribe',
    alt: 'Tribe Academy, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Tribe Academy Twitter',
  },
  {
    srcref: 'gpc',
    link: 'https://www.graphpapercapital.xyz/',
    alt: 'Graph Paper Capital, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Graph Paper Capital Website',
  },
  {
    srcref: 'h4bengal',
    link: 'https://twitter.com/hack4bengal',
    alt: 'Hack4Bengal, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Hack4Bengal Twitter',
  },
  {
    srcref: 'wx',
    link: 'https://chat.whatsapp.com/HAiXuvHqblJA7C%E2%80%A6',
    alt: 'WebCrux, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit WebCrux Whatsapp',
  },
  {
    srcref: 'phoenixguild',
    link: 'https://twitter.com/PhoenixGuildHQ',
    alt: 'Phoenix Guild, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Phoenix Guild Twitter',
  },
  {
    srcref: 'diversion',
    link: 'https://twitter.com/Diversion2k23',
    alt: 'Diversion, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Diversion Twitter',
  },
  {
    srcref: 'irlamigo',
    link: 'https://twitter.com/irl_amigo',
    alt: 'IRL Amigo, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit IRL Amigo Twitter',
  },
  {
    srcref: 'w3cg',
    link: 'https://twitter.com/Bhopal_DAO',
    alt: 'Web3 Connect Global, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Web3 Connect Global Twitter',
  },
  {
    srcref: 'blockchained',
    link: 'https://twitter.com/blockchainedind',
    alt: 'Blockchained India, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Blockchained India Twitter',
  },
  {
    srcref: 'foundership',
    link: 'https://twitter.com/FoundershipHQ',
    alt: 'Foundership HQ, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Foundership HQ Twitter',
  },
  {
    srcref: 'ogclub',
    link: 'https://twitter.com/OgclubDAO',
    alt: 'OG Club DAO, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit OG Club DAO Twitter',
  },
  {
    srcref: 'punedao',
    link: 'https://twitter.com/pune_dao',
    alt: 'Pune DAO, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Pune DAO Twitter',
  },
  {
    srcref: 'kba',
    link: 'https://t.me/+BQp6kdcPF1c5MDA1',
    alt: 'Kerala Blockchain Academy (KBA), Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Kerala Blockchain Academy (KBA) Twitter',
  },
  {
    srcref: 'updao',
    link: 'https://twitter.com/uttarpradeshdao',
    alt: 'UP DAO, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit UP DAO Twitter',
  },
  {
    srcref: 'w3j',
    link: 'https://twitter.com/web3jaipur',
    alt: 'Web3 Jaipur, Community Partner of Push, #BRBIndia, pan-India dev tour',
    title: 'Visit Web3 Jaipur Twitter',
  }
];
