export const brbOnlineList = [
  {
    srcref: 'filecoin',
    link: 'https://www.youtube.com/live/u_c-rwPCTbw?si=A-yymxnDCFtbQprT',
    alt: 'Filecoin, Partner of Push, #BRBIndia, pan-India dev tour',
    text: 'Learn how to develop DataDAOs to Incentivize data contributions and storage',
    date: 'Fri, Nov 3, 2023',
    time: '7:30PM @ Push Protocol YouTube',
  },
  {
    srcref: 'chainsafe',
    link: 'https://www.youtube.com/live/BUuVt1gWMRA?si=6BB8qFemDzdkQWwo',
    alt: 'Chain safe, Partner of Push, #BRBIndia, pan-India dev tour',
    text: 'Develop plugins for web3.js 4.x, enhancing Ethereum sectors like NFTs, DeFi, Gaming, etc',
    date: 'Sat, Nov 4, 2023',
    time: '7:30PM @ Push Protocol YouTube',
  },
  {
    srcref: 'thegraph',
    link: 'https://www.youtube.com/live/Zmd26545Mck?si=ybV5syxEJ_l6ttgf',
    alt: 'The Graph, Partner of Push, #BRBIndia, pan-India dev tour',
    text: 'Learn to organize and serve blockchain data for your application using subgraphs',
    date: 'Thu, Nov 9, 2023',
    time: '7:30PM @ Push Protocol YouTube',
  },

  {
    srcref: 'shardeum',
    link: 'https://www.youtube.com/live/2CasCVJ6Fy8?si=k5QZ5RVrmF-XGwZ3',
    alt: 'Shardeum, Partner of Push, #BRBIndia, pan-India dev tour',
    text: 'Learn to build an Automated Market Maker (AMM) optimized for parallel processing',
    date: 'Thu, Nov 16, 2023',
    time: '7:30PM @ Push Protocol YouTube',
  },
  {
    srcref: 'biconomy',
    link: 'https://www.youtube.com/live/B6P72iUC7Ko?si=SMV4xy66_zNc6sMJ',
    alt: 'Biconomy, Partner of Push, #BRBIndia, pan-India dev tour',
    text: 'Learn to build a new validation module to use with the Biconomy smart accounts',
    date: 'Fri, Nov 17, 2023',
    time: '7:30PM @ Push Protocol YouTube',
  },
  {
    srcref: 'aragon',
    link: 'https://www.youtube.com/live/V0XaCsq7TRA?si=A5_kU-oN5yEsuNLC',
    alt: 'Aragon, Partner of Push, #BRBIndia, pan-India dev tour',
    text: 'Learn to build DAO solutions',
    date: 'Fri, Nov 24, 2023',
    time: '7:30PM @ Push Protocol YouTube',
  },
  {
    srcref: 'polygon',
    link: 'https://www.youtube.com/live/eWEGkDaGkL0?si=9nnIVIxXLEnMXRsQ',
    alt: 'Polygon, Partner of Push, #BRBIndia, pan-India dev tour',
    text: 'Learn to Implement OpenZeppelin to vote on zkEVM from Ethereum or Polygon PoS',
    date: 'Sat, Nov 25, 2023',
    time: '7:30PM @ Push Protocol YouTube',
  },
];
