/* eslint-disable indent */

export const citiesList = [
  [
    {
      srcref: 'kolkata',
      place: 'Kolkata',
      date: '2 Sept 2023',
      link: 'https://www.lu.ma/brb-kolkata',
      alt: 'Kolkata, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Kolkata, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#299EC2',
      hasEnded: false,
    },
    {
      srcref: 'indore',
      place: 'Indore',
      date: '4 Sept 2023',
      link: 'https://www.lu.ma/brb-indore',
      alt: 'Indore, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Indore, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#16837C',
      hasEnded: false,
    },
  ],
  [
    {
      srcref: 'kochi',
      place: 'Kochi',
      date: '9 Sept 2023',
      link: 'https://www.lu.ma/brb-kochi',
      alt: 'Kochi, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Kochi, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#194395',
      hasEnded: false,
    },
    {
      srcref: 'coimbatore',
      place: 'Coimbatore',
      date: '11 Sept 2023',
      link: 'https://www.lu.ma/brb-coimbatore',
      alt: 'Coimbature, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Coimbature, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#299EC2',
      hasEnded: false,
    },
  ],
  [
    {
      srcref: 'trivandrum',
      place: 'Trivandrum',
      date: '16 Sept 2023',
      link: 'https://www.lu.ma/brb-trivandrum',
      alt: 'Trivandrum, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Trivandrum, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#7A3DA9',
      hasEnded: false,
    },
    {
      srcref: 'chennai',
      place: 'Chennai',
      date: '19 Sep 2023',
      link: 'https://www.lu.ma/brb-chennai',
      alt: 'Chennai, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Chennai, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#E26059',
      hasEnded: false,
    }
  ],
  [
    {
      srcref: 'pune',
      place: 'Pune',
      date: '23 Sept 2023',
      link: 'https://www.lu.ma/brb-pune',
      alt: 'Pune, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Pune, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#E26059',
      hasEnded: false,
    },
    {
      srcref: 'hyderabad',
      place: 'Hyderabad',
      date: '25 Sept 2023',
      link: 'https://www.lu.ma/brb-hyderabad',
      alt: 'Hyderabad, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Hyderabad, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#194395',
      hasEnded: false,
    },
  ],
  [
    {
      srcref: 'ahmedabad',
      place: 'Ahmedabad',
      date: '30 Sept 2023',
      link: 'https://www.lu.ma/brb-ahmedabad',
      alt: 'Ahmedabad, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Ahmedabad, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#194395',
      hasEnded: false,
    },
    {
      srcref: 'mumbai',
      place: 'Mumbai',
      date: '7 Oct 2023',
      link: 'https://www.lu.ma/brb-mumbai',
      alt: 'Mumbai, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Mumbai, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#7A3DA9',
      hasEnded: false,
    },
  ],
  [
    {
      srcref: 'bhopal',
      place: 'Bhopal',
      date: '16 Oct 2023',
      link: 'https://www.lu.ma/brb-bhopal',
      alt: 'Bhopal, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Bhopal, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#16837C',
      hasEnded: false,
    },
    {
      srcref: 'jaipur',
      place: 'Jaipur',
      date: '21 Oct 2023',
      link: 'https://www.lu.ma/brb-jaipur',
      alt: 'Jaipur, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Jaipur, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#16837C',
      hasEnded: false,
    },
  ],
  [
    {
      srcref: 'delhi_north',
      place: 'Delhi',
      date: '4 Nov 2023',
      link: 'https://www.lu.ma/brb-delhi',
      alt: 'Delhi, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Delhi, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#194395',
      hasEnded: false,
    },
    {
      srcref: 'lucknow',
      place: 'Lucknow',
      date: '17 Nov 2023',
      link: 'https://www.lu.ma/brb-lucknow',
      alt: 'Lucknow, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Lucknow, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#2E7D5C',
      hasEnded: false,
    },
  ],
  [
    {
      srcref: 'kanpur',
      place: 'Kanpur',
      date: 'TBA',
      link: 'https://www.lu.ma/brb-kanpur',
      alt: 'Kanpur, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Kanpur, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#E26059',
      hasEnded: false,
    },
    {
      srcref: 'agra',
      place: 'Agra',
      date: 'TBA',
      link: 'https://www.lu.ma/brb-agra',
      alt: 'Agra, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Agra, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#194395',
      hasEnded: false,
    },
  ],
  [
    {
      srcref: 'dehradun',
      place: 'Dehradun',
      date: 'TBA',
      link: 'https://lu.ma/brb-dehradun',
      alt: 'Dehradun, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Dehradun, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#7A3DA9',
      hasEnded: false,
    },
    {
      srcref: 'bengaluru',
      place: 'Bengaluru',
      date: 'TBA',
      link: 'https://www.lu.ma/brb-benagaluru',
      alt: 'Bengaluru, India illustration for #BRB #BRBIndia event link',
      title: 'Lu.ma event page for Bengaluru, India for dev tour of Push. #BRBIndia campaign of Push',
      backgroundColor: '#299EC2',
      hasEnded: false,
    },
  ],
];
