const featuredList = {
  featured: {
    esp: {
      title: "Ethereum Push Notification featured on Official Ethereum Blog",
      href: "https://blog.ethereum.org/2020/08/19/esp-beyond-grants/",
      src: "esp",
      alt: "Ethereum Support Program Logo",
      bg: false,
    },
    cnbc: {
      title: "CNBC interviews Harsh on EPNS and future of crypto",
      href: "https://twitter.com/CNBCTV18News/status/1418863890662887430?s=20",
      src: "cnbc",
      alt: "CNBC Logo",
      bg: false,
    },
    forbes: {
      title: "Forbes India talks with Harsh about EPNS",
      href: "https://twitter.com/forbes_india/status/1427857510900269067",
      src: "forbes",
      alt: "Forbes Logo",
      bg: false,
    },
    cointelegraph: {
      title: "Coin Telegraph talks about Push Notifications from Ethereum Push Notification Service",
      href: "https://cointelegraph.com/news/dapps-can-now-send-push-notifications-to-ethereum-wallet-users",
      src: "cointelegraph",
      alt: "Coin Telegraph Logo",
      bg: false,
    },
    hackernoon: {
      title: "Hackernoon interview on how Ethereum Push Notifications Will Pull Blockchain Out of the Stone Age",
      href: "https://hackernoon.com/push-notifications-will-pull-blockchain-out-of-the-stone-age-of-communication-unhashed-1-ql1f33d6",
      src: "hackernoon",
      alt: "Hackernoon Logo",
      bg: false,
    },
    epicenter: {
      title: "Epicenter podcast about Ethereum Push Notification Service – The Decentralized Notification Protocol",
      href: "https://epicenter.tv/episodes/377",
      src: "epicenter",
      alt: "Epicenter Logo",
      bg: false,
    },    
  },
  featuredSecondary: {
    theblock: {
      title: "The Block Crypto writes about EPNS: Balaji Srinivasan, Gitcoin co-founder back $750K seed round for decentralized notification system on Ethereum",
      href: "https://www.theblockcrypto.com/linked/86953/ethereum-notification-system-seed-funding",
      src: "theblock",
      alt: "The Block Crypto Logo",
      bg: false,
    },
    defiprime: {
      title: "Harsh Rajat, our founder talks about future of banking, EPNS protocol incentives and where is a business model for decentralized push notifications.",
      href: "https://defiprime.com/ethereum-push-notification-service",
      src: "defiprime",
      alt: "DeFiPrime Logo",
      bg: false,
    },
    coinlist: {
      title: "Ethereum Push Notification Service graduates from CoinList Seed Batch 2020",
      href: "https://blog.coinlist.co/introducing-the-coinlist-seed-fall-2020-batch/",
      src: "coinlist",
      alt: "Coinlist Logo",
      bg: "#e20880",
    },
    dailygwei: {
      title: "Anthony Sassano talks about Ethereum Push Notification Service (EPNS) Project on the DailyGWEI Channel",
      href: "https://www.youtube.com/watch?v=4k159Kob0Cs",
      src: "dailygwei",
      alt: "DailyGWEI Logo",
      bg: false,
    },
    gitcoin: {
      title: "Ethereum Push Notification Service selected as top 20 project and unvelied at fireside",
      href: "https://twitter.com/epnsproject/status/1299018919143849984?s=20",
      src: "kernel",
      alt: "Gitcoin Kernel Logo",
      bg: false,
    },    
  },
  drilldown: {
    yourstory: {
      title: "Yourstory talks about EPNS and why blockchain push notifications are important",
      href: "https://yourstory.com/2020/11/husband-wife-duo-need-blockchain-push-notifications",
      src: "yourstory",
      alt: "YourStory Logo",
      bg: false,
    },
    ideo: {
      title: "IDEO Collab selected and mentored Ethereum Push Notification Service as 30 projects from 120 projects for Product Validation Day",
      href: "https://medium.com/@ideovc/hello-its-your-users-calling-7599c679e28d",
      src: "ideo",
      alt: "IDEO Collab Product Validation Day Logo",
      bg: false,
    },
    ethhub: {
      title: "Anthony Sassano talks about Ethereum Push Notification Service (EPNS) Project on ETHHub",
      href: "https://podcast.ethhub.io/ethhub-weekly-119-yield-farming-defi-valuations-on-the-rise-eths-value-prop-epns-introduced-consensys-staking-as-a-service-reddits-scaling-ethereum-challenge-and-matter-labs-zk-sync",
      src: "ethhub",
      alt: "EthHub Logo",
      bg: false,
    },
    defidad: {
      title: "DeFi Dad upcoming podcast about EPNS",
      href: "https://twitter.com/DeFi_Dad/status/1297544923219189760?s=20",
      src: "defidad",
      alt: "DeFiDad Logo",
      bg: false,
    },
    coincrunch: {
      title: "CoinCrunch and EPNS Team talks everything from setting up metamask to wallet to #Web3Notif",
      href: "https://www.youtube.com/watch?v=WkgKTy3i8F4",
      src: "coincrunch",
      alt: "CoinCrunch India Logo",
      bg: false,
    },
    nuggetnews: {
      title: "Alex Saunders talks about EPNS on Nugget News",
      href: "https://www.youtube.com/watch?v=ptDzAm62ATg&feature=youtu.be",
      src: "nuggetnews",
      alt: "Nugget News Logo",
      bg: false,
    }, 
    edcon: {
      title: "EDCON Panel featuring Harsh Rajat, founder, EPNS talks about DeFi Cross Composability",
      href: "https://www.edcon.io/#maodian",
      src: "edcon",
      alt: "Edcon Logo",
      bg: false,
    },
    inc42: {
      title: "INC42 talks about epnsproject and how dApps can benefit from it",
      href: "https://inc42.com/buzz/cryptocurrency-this-week-wazirx-talks-defi-indias-crypto-ban-more/",
      src: "inc42",
      alt: "INC42 Logo",
      bg: false,
    },
    paradigm: {
      title: "Paradigm features epnsproject",
      href: "https://medium.com/paradigm-fund/ethereum-biweekly-vol-46-ecosystem-and-projects-updates-development-tools-and-research-articles-c2732e1502aa",
      src: "paradigm",
      alt: "Paradigm Logo",
      bg: false,
    },
    paradigm: {
      title: "DefiPulse includes epnsproject in their esteemed list!",
      href: "https://defipulse.com/defi-list",
      src: "defipulse",
      alt: "DefiPulse Logo",
      bg: "#e20880",
    },
    cryptodose: {
      title: "CryptoDose covers EPNS Seed Round",
      href: "https://cryptodose.co/ethereum-based-web3-push-notifications-service-epns-raises-750k-seed/",
      src: "cryptodose",
      alt: "CryptoDose Logo",
      bg: false,
    },
    mojkripto: {
      title: "MojKripto deep dives into Ethereum Push Notification Service and the team behind it!",
      href: "https://mojkripto.com/ethereum-push-notification-service-epns-interview/?lang=en",
      src: "mojkripto",
      alt: "MojKrypto Logo",
      bg: false,
    }
  }
}


export default featuredList;
