export const HeaderList = {
  products: [
    {
      title: 'header.products.link1.title',
      subtitle: 'header.products.link1.subtitle',
      srcrefoff: 'inbox-icon-off',
      id: 'notification',
    },
    {
      title: 'header.products.link2.title',
      subtitle: 'header.products.link2.subtitle',
      srcrefoff: 'chat-icon-off',
      id: 'chat',
    },
    {
      title: 'header.products.link3.title',
      subtitle: 'header.products.link3.subtitle',
      srcrefoff: 'video-icon-off',
      id: 'otherfeatures',
    },
    {
      title: 'header.products.link4.title',
      subtitle: 'header.products.link4.subtitle',
      srcrefoff: 'spaces-icon-off',
      id: 'otherfeatures',
    },
  ],
  developers: [
    {
      title: 'header.developers.link1.title',
      subtitle: 'header.developers.link1.subtitle',
      srcrefoff: 'docs-icon-off',
      href: '/docs',
      target: '_blank',
    },
    {
      title: 'header.developers.link2.title',
      subtitle: 'header.developers.link2.subtitle',
      srcrefoff: 'examples-icon-off',
      href: 'https://github.com/push-protocol/push-sdk/tree/main/packages/examples',
    },
    {
      title: 'header.developers.link3.title',
      subtitle: 'header.developers.link3.subtitle',
      srcrefoff: 'inbox-icon-off',
      href: '/docs/notifications/quickstart/',
      target: '_blank',
    },
    {
      title: 'header.developers.link4.title',
      subtitle: 'header.developers.link4.subtitle',
      srcrefoff: 'chat-icon-off',
      href: '/docs/chat/quickstart/',
      target: '_blank',
    },
    {
      title: 'header.developers.link5.title',
      subtitle: 'header.developers.link5.subtitle',
      srcrefoff: 'hacker-icon-off',
      href: '/docs/hackers/',
      target: '_blank',
    },
    {
      title: 'header.developers.link6.title',
      subtitle: 'header.developers.link6.subtitle',
      tagitem: {
        text: 'NEW',
      },
      srcrefoff: 'react-icon-off',
      href: '/docs/video/playground/push-react-component-playground-example/',
      target: '_blank',
    },
    {
      title: 'header.developers.link7.title',
      subtitle: 'header.developers.link7.subtitle',
      srcrefoff: 'discord-icon-off',
      href: 'https://discord.gg/pushprotocol',
    },
  ],
  community: [
    {
      title: 'header.community.link1.title',
      subtitle: 'header.community.link1.subtitle',
      href: '/frens',
      target: '_self',
    },
    {
      title: 'header.community.link2.title',
      subtitle: 'header.community.link2.subtitle',
      href: '/docs/dao',
      target: '_self',
    },
    {
      title: 'header.community.link3.title',
      subtitle: 'header.community.link3.subtitle',
      href: '/docs/dao/contribute-to-push-dao/contribute-push-grants/',
      target: '_self',
    },
    {
      title: 'header.community.link4.title',
      subtitle: 'header.community.link4.subtitle',
      href: '/brb',
      target: '_self',
    },
  ],
  resources: [
    {
      title: 'header.resources.link1.title',
      subtitle: 'header.resources.link1.subtitle',
      href: '/blog',
      target: '_self',
    },
    {
      title: 'header.resources.link2.title',
      subtitle: 'header.resources.link2.subtitle',
      href: '/faq',
      target: '_self',
    },
    {
      title: 'header.resources.link3.title',
      subtitle: 'header.resources.link3.subtitle',
      tagitem: {
        text: 'NEW',
      },
      href: '/docs/roadmap',
      target: '_self',
    },
    {
      title: 'header.resources.link4.title',
      subtitle: 'header.resources.link4.subtitle',
      id: 'tokenomics',
    },
  ],
  docshub: [
    {
      title: 'Notification Docs',
      subtitle: 'Web3 native notification alerts',
      srcrefoff: 'inbox-icon-off',
      href: 'https://comms.push.org/docs/notifications',
      target: '_blank',
    },
    {
      title: 'Chat Docs',
      subtitle: 'Web3 native chat protocol with groups',
      srcrefoff: 'chat-icon-off',
      href: 'https://comms.push.org/docs/chat',
      target: '_blank',
    },
    {
      title: 'Video Docs',
      subtitle: 'Decentralized video calls',
      srcrefoff: 'video-icon-off',
      href: 'https://comms.push.org/docs/video',
      target: '_blank',
    },
    {
      title: 'Spaces Docs',
      subtitle: 'Decentralized audio streaming',
      srcrefoff: 'spaces-icon-off',
      href: 'https://www.npmjs.com/package/@pushprotocol/restapi#for-spaces',
      target: '_blank',
    },
    {
      title: 'Push Home',
      subtitle: 'Back to Push Homepage',
      srcrefoff: 'home',
      href: '/',
      target: '_self',
    },
  ],
};
