export const InvList = {
  top: [
    {
      srcref: 'jump',
      id: 'jump',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Jump',
    },
    {
      srcref: 'parafi',
      id: 'parafi',
      title: null,
      subtitle: null,
      alt: 'Push Investor - ParaFi',
    },
    {
      srcref: 'true',
      id: 'true',
      title: null,
      subtitle: null,
      alt: 'Push Investor - True',
    },
    {
      srcref: 'IOSG',
      id: 'iosg',
      title: null,
      subtitle: null,
      alt: 'Push Investor - IOSG',
    },
    {
      srcref: '4rc',
      id: '4rc',
      title: null,
      subtitle: null,
      alt: 'Push Investor - 4RC',
    },
    {
      srcref: 'The-LAO',
      id: 'the-lao',
      title: null,
      subtitle: null,
      alt: 'Push Investor - The LAO',
    },
    {
      srcref: 'vcACapital',
      id: 'a_capital',
      title: null,
      subtitle: null,
      alt: 'Push Investor - A Capital',
    },
    {
      srcref: 'vcSandeep',
      id: 'sandeep',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Sandeep',
    },
    {
      srcref: 'vcAndrew',
      id: 'andrew',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Andrew Keys',
    }
  ],
  bottom: [
    {
      srcref: 'tigerglobal',
      id: 'tigerglobal',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Tiger Global',
    },
    {
      srcref: 'binance',
      id: 'binancelabs',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Binance Labs',
    },
    {
      srcref: 'vcBalaji',
      id: 'balaji',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Balaji Srinivasan',
    },
    {
      srcref: 'polygon-studios',
      id: 'polygonstudios',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Polygon Studios',
    },
    {
      srcref: 'ryze',
      id: 'ryze',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Ryze',
    },
    {
      srcref: 'vcKenneth',
      id: 'kenneth',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Kenneth Ng',
    },
    {
      srcref: 'vcDefi-dad',
      id: 'defi-dad',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Defi dad',
    },
    {
      srcref: 'vcAnton',
      id: 'anton',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Anton Bukov',
    },
    {
      srcref: 'vcScott',
      id: 'scott',
      title: null,
      subtitle: null,
      alt: 'Push Investor - Scott Moore',
    },
    // {
    //   srcref: 'sandeep',
    //   id: 'sandeep',
    //   title: 'Sandeep N.',
    //   subtitle: 'Co-founder Polygon',
    //   alt: 'Push Investor - Sandeep Nailwal',
    // },
    // {
    //   srcref: 'andrew',
    //   id: 'andrew',
    //   title: 'Andrew K.',
    //   subtitle: 'Angel Investor',
    //   alt: 'Push Investor - Andrew K.',
    // },
    // {
    //   srcref: '4rc',
    //   id: '4rc',
    //   title: null,
    //   subtitle: null,
    //   alt: 'Push Investor - 4RC',
    // },
  ]
}