export const ShowcaseList = {
  top: {
    left: {
      upper: [
        {
          srcref: 'bankless',
          alt: 'Powered by Push Chain - Bankless Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'decentraland',
          alt: 'Powered by Push Chain - Decentraland Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'shapeshift',
          alt: 'Powered by Push Chain - Shapeshift Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'uniswap',
          alt: 'Powered by Push Chain - Uniswap Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'oasis',
          alt: 'Powered by Push Chain - Oasis Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
    mid: {
      upper: [
        {
          srcref: 'snapshot',
          alt: 'Powered by Push Chain - Snapshot Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'ens',
          alt: 'Powered by Push Chain - ENS Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'bancor',
          alt: 'Powered by Push Chain - Bancor Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'aragon',
          alt: 'Powered by Push Chain - Aragon Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'makerdao',
          alt: 'Powered by Push Chain - MakerDAO Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'earnifi',
          alt: 'Powered by Push Chain - EarniFi Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'cryptocurrencyjobs',
          alt: 'Powered by Push Chain - Cryptocurrency Jobs Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'aave',
          alt: 'Powered by Push Chain - AAVE Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'rekt',
          alt: 'Powered by Push Chain - Rekt Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
  },
  bottom: {
    left: {
      upper: [
        {
          srcref: 'metastable',
          alt: 'Powered by Push Chain - Meta Stable Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: '1inch',
          alt: 'Powered by Push Chain - 1Inch Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'secondlive',
          alt: 'Powered by Push Chain - Second Live Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'atlendis',
          alt: 'Powered by Push Chain - Atlendis Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'apeswap',
          alt: 'Powered by Push Chain - Apeswap Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
    mid: {
      upper: [
        {
          srcref: 'qidao',
          alt: 'Powered by Push Chain - QiDAO Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'dydx',
          alt: 'Powered by Push Chain - DyDx Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'lepasametaverse',
          alt: 'Powered by Push Chain - Lepasa Metaverse Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'orionprotocol',
          alt: 'Powered by Push Chain - Orion Protocol Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'symphonyfinance',
          alt: 'Powered by Push Chain - Symphony Finance Labs Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'coindesk',
          alt: 'Powered by Push Chain - Coindesk Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'kybernetwork',
          alt: 'Powered by Push Chain - Kyber Network Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'lifi',
          alt: 'Powered by Push Chain - LiFi Protocol Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'dd',
          alt: 'Powered by Push Chain - Developer DAO Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
  },
  left: {
    left: {
      upper: [
        {
          srcref: 'unstoppable',
          alt: 'Powered by Push Chain - Unstoppable Domains Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'mahadao',
          alt: 'Powered by Push Chain - MahaDAO Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'proofofhumanity',
          alt: 'Powered by Push Chain - Proof of Humanity Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'sushi',
          alt: 'Powered by Push Chain - Sushiswap Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
  },
  right: {
    left: {
      upper: [
        {
          srcref: 'polychainmonsters',
          alt: 'Powered by Push Chain - Polychain Monsters Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'pooltogether',
          alt: 'Powered by Push Chain - Pool Together Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'ethsign',
          alt: 'Powered by Push Chain - ETHSign Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'lensprotocol',
          alt: 'Powered by Push Chain - Lens Protocol Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
  },
};

export const ShowcaseResponsiveList = {
  top: [
    {
      srcref: 'bankless',
      alt: 'Powered by Push Chain - Bankless Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'decentraland',
      alt: 'Powered by Push Chain - Decentraland Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'uniswap',
      alt: 'Powered by Push Chain - Uniswap Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'aave',
      alt: 'Powered by Push Chain - AAVE Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'rekt',
      alt: 'Powered by Push Chain - Rekt Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'sushi',
      alt: 'Powered by Push Chain - Sushiswap Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'unstoppable',
      alt: 'Powered by Push Chain - Unstoppable Domains Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'proofofhumanity',
      alt: 'Powered by Push Chain - Proof of Humanity Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
  ],
  bottom: [
    {
      srcref: 'lensprotocol',
      alt: 'Powered by Push Chain - Lens Protocol Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: '1inch',
      alt: 'Powered by Push Chain - 1Inch Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'coindesk',
      alt: 'Powered by Push Chain - Coindesk Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'ens',
      alt: 'Powered by Push Chain - ENS Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'bancor',
      alt: 'Powered by Push Chain - Bancor Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'aragon',
      alt: 'Powered by Push Chain - Aragon Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'qidao',
      alt: 'Powered by Push Chain - QiDAO Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'dydx',
      alt: 'Powered by Push Chain - DyDx Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
  ],
};

// Additional showcase list
// [
//   {
//     srcref: 'anglelabs',
//     alt: 'Powered by Push Chain - Angle Labs Logo',
//   },
//   {
//     srcref: 'flipside',
//     alt: 'Powered by Push Chain - Flipside Logo',
//   },
//   {
//     srcref: 'goodghosting',
//     alt: 'Powered by Push Chain - Good Ghosting Logo',
//   },
//   {
//     srcref: 'gro',
//     alt: 'Powered by Push Chain - Gro Logo',
//   },
//   {
//     srcref: 'meanfinance',
//     alt: 'Powered by Push Chain - Mean Finance Logo',
//   },
//   {
//     srcref: 'mover',
//     alt: 'Powered by Push Chain - Mover Logo',
//   },
//   {
//     srcref: 'podsfinance',
//     alt: 'Powered by Push Chain - Pods Finance Logo',
//   },
//   {
//     srcref: 'thena',
//     alt: 'Powered by Push Chain - Thena Logo',
//   },
//   {
//     srcref: 'wormbat',
//     alt: 'Powered by Push Chain - Wormbat Logo',
//   },
//   {
//     srcref: 'zeroswap',
//     alt: 'Powered by Push Chain - Zeroswap Logo',
//   },
// ]
