export const ShowcaseList = {
  top: {
    left: {
      upper: [
        {
          srcref: 'bankless',
          alt: 'Powered by Push Protocol - Bankless Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'decentraland',
          alt: 'Powered by Push Protocol - Decentraland Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'shapeshift',
          alt: 'Powered by Push Protocol - Shapeshift Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'uniswap',
          alt: 'Powered by Push Protocol - Uniswap Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'oasis',
          alt: 'Powered by Push Protocol - Oasis Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
    mid: {
      upper: [
        {
          srcref: 'snapshot',
          alt: 'Powered by Push Protocol - Snapshot Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'ens',
          alt: 'Powered by Push Protocol - ENS Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'bancor',
          alt: 'Powered by Push Protocol - Bancor Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'aragon',
          alt: 'Powered by Push Protocol - Aragon Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'makerdao',
          alt: 'Powered by Push Protocol - MakerDAO Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'earnifi',
          alt: 'Powered by Push Protocol - EarniFi Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'cryptocurrencyjobs',
          alt: 'Powered by Push Protocol - Cryptocurrency Jobs Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'aave',
          alt: 'Powered by Push Protocol - AAVE Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'rekt',
          alt: 'Powered by Push Protocol - Rekt Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
  },
  bottom: {
    left: {
      upper: [
        {
          srcref: 'metastable',
          alt: 'Powered by Push Protocol - Meta Stable Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: '1inch',
          alt: 'Powered by Push Protocol - 1Inch Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'secondlive',
          alt: 'Powered by Push Protocol - Second Live Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'atlendis',
          alt: 'Powered by Push Protocol - Atlendis Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'apeswap',
          alt: 'Powered by Push Protocol - Apeswap Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
    mid: {
      upper: [
        {
          srcref: 'qidao',
          alt: 'Powered by Push Protocol - QiDAO Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'dydx',
          alt: 'Powered by Push Protocol - DyDx Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'lepasametaverse',
          alt: 'Powered by Push Protocol - Lepasa Metaverse Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'orionprotocol',
          alt: 'Powered by Push Protocol - Orion Protocol Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'symphonyfinance',
          alt: 'Powered by Push Protocol - Symphony Finance Labs Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'coindesk',
          alt: 'Powered by Push Protocol - Coindesk Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
        {
          srcref: 'kybernetwork',
          alt: 'Powered by Push Protocol - Kyber Network Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'lifi',
          alt: 'Powered by Push Protocol - LiFi Protocol Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
        {
          srcref: 'dd',
          alt: 'Powered by Push Protocol - Developer DAO Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
  },
  left: {
    left: {
      upper: [
        {
          srcref: 'unstoppable',
          alt: 'Powered by Push Protocol - Unstoppable Domains Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'mahadao',
          alt: 'Powered by Push Protocol - MahaDAO Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'proofofhumanity',
          alt: 'Powered by Push Protocol - Proof of Humanity Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'sushi',
          alt: 'Powered by Push Protocol - Sushiswap Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
  },
  right: {
    left: {
      upper: [
        {
          srcref: 'polychainmonsters',
          alt: 'Powered by Push Protocol - Polychain Monsters Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'pooltogether',
          alt: 'Powered by Push Protocol - Pool Together Logo',
          width: '96px',
          height: '96px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
    right: {
      upper: [
        {
          srcref: 'ethsign',
          alt: 'Powered by Push Protocol - ETHSign Logo',
          width: '0px',
          height: '0px',
          margin: '0px',
          opacity: '0',
          class: 'showcaseItem',
        },
      ],
      lower: [
        {
          srcref: 'diamante',
          alt: 'Powered by Push Protocol - Diamante Logo',
          width: '178px',
          height: '178px',
          margin: '14px',
          opacity: '1',
          class: 'showcaseItem',
        },
      ],
    },
  },
};

export const ShowcaseResponsiveList = {
  top: [
    {
      srcref: 'bankless',
      alt: 'Powered by Push Protocol - Bankless Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'decentraland',
      alt: 'Powered by Push Protocol - Decentraland Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'uniswap',
      alt: 'Powered by Push Protocol - Uniswap Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'aave',
      alt: 'Powered by Push Protocol - AAVE Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'rekt',
      alt: 'Powered by Push Protocol - Rekt Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'sushi',
      alt: 'Powered by Push Protocol - Sushiswap Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'unstoppable',
      alt: 'Powered by Push Protocol - Unstoppable Domains Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'proofofhumanity',
      alt: 'Powered by Push Protocol - Proof of Humanity Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
  ],
  bottom: [
    {
      srcref: 'diamante',
      alt: 'Powered by Push Protocol - Diamante Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: '1inch',
      alt: 'Powered by Push Protocol - 1Inch Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'coindesk',
      alt: 'Powered by Push Protocol - Coindesk Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'ens',
      alt: 'Powered by Push Protocol - ENS Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'bancor',
      alt: 'Powered by Push Protocol - Bancor Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'aragon',
      alt: 'Powered by Push Protocol - Aragon Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'qidao',
      alt: 'Powered by Push Protocol - QiDAO Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
    {
      srcref: 'dydx',
      alt: 'Powered by Push Protocol - DyDx Logo',
      width: '96px',
      height: '96px',
      class: '',
    },
  ],
};

// Additional showcase list
// [
//   {
//     srcref: 'anglelabs',
//     alt: 'Powered by Push Protocol - Angle Labs Logo',
//   },
//   {
//     srcref: 'flipside',
//     alt: 'Powered by Push Protocol - Flipside Logo',
//   },
//   {
//     srcref: 'goodghosting',
//     alt: 'Powered by Push Protocol - Good Ghosting Logo',
//   },
//   {
//     srcref: 'gro',
//     alt: 'Powered by Push Protocol - Gro Logo',
//   },
//   {
//     srcref: 'meanfinance',
//     alt: 'Powered by Push Protocol - Mean Finance Logo',
//   },
//   {
//     srcref: 'mover',
//     alt: 'Powered by Push Protocol - Mover Logo',
//   },
//   {
//     srcref: 'podsfinance',
//     alt: 'Powered by Push Protocol - Pods Finance Logo',
//   },
//   {
//     srcref: 'thena',
//     alt: 'Powered by Push Protocol - Thena Logo',
//   },
//   {
//     srcref: 'wormbat',
//     alt: 'Powered by Push Protocol - Wormbat Logo',
//   },
//   {
//     srcref: 'zeroswap',
//     alt: 'Powered by Push Protocol - Zeroswap Logo',
//   },
// ]
