const investorsList = {
  vcs: {
    true: {
      title: "Learn about our Investor - True Ventures",
      href: "https://trueventures.com/",
      src: "trueventures",
      alt: "Logo of True Ventures, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
    binance: {
      title: "Learn about our Investor - Binance",
      href: "https://binance.com/",
      src: "binance",
      alt: "Logo of Binance, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
    mysterio: {
      title: "Learn about our Investor - Mysterio",
      href: "#",
      src: "mysterio",
      alt: "Logo of Mysterio, Fund / Angel / Nothingness",
      name: false,
      job: false,
      disabled: true,
    },
    iosg: {
      title: "Learn about our Investor - iOSG",
      href: "https://iosg.vc/",
      src: "iosgventures",
      alt: "Logo of iOSG Ventures, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
    thelao: {
      title: "Learn about our Investor - TheLAO",
      href: "https://www.thelao.io/",
      src: "thelao",
      alt: "Logo of The LAO, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
    metacartel: {
      title: "Learn about our Investor - Meta Cartel",
      href: "https://www.metacartel.org/",
      src: "metacartel",
      alt: "Logo of Meta Cartel Ventures, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
    ldcap: {
      title: "Learn about our Investor - LD Capital",
      href: "https://ldcap.com",
      src: "ldcapital",
      alt: "Logo of LD Capital, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
    brcapital: {
      title: "Learn about our Investor - BR Capital",
      href: "https://br.capital/",
      src: "brcapital",
      alt: "Logo of BR Capital, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
    bitscale: {
      title: "Learn about our Investor - Bitscale Capital",
      href: "https://bitscale.capital/",
      src: "bitscale",
      alt: "Logo of Bitscale Capital, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
    bixin: {
      title: "Learn about our Investor - Bixin Ventures",
      href: "http://bixincapital.com/",
      src: "bixinventures",
      alt: "Logo of Bixin Ventures, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
    fourthrev: {
      title: "Learn about our Investor - Fourth Revolution Capital",
      href: "https://fourthrevolution.capital/",
      src: "fourthrevolution",
      alt: "Logo of Fourth Revolution Capital, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
    d64: {
      title: "Learn about our Investor - D64",
      href: "https://d64.vc/",
      src: "proofsystems_d64",
      alt: "Logo of D64, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
  },
  angels: {
    balaji: {
      title: "Learn about our Investor - Balaji S. Srinivasan, Serial Entreprenuer",
      href: "https://balajis.com/",
      src: "balaji",
      alt: "Sketch of Investor - Balaji S. Srinivasan, Serial Entrepreneur",
      name: "Balaji S. Srinivasan",
      job: "Serial Entrepreneur",
      disabled: false,
    },
    ken: {
      title: "Learn about our Investor - Kenneth Ng, Ethereum Foundation",
      href: "https://twitter.com/nkennethk",
      src: "ken",
      alt: "Sketch of Investor - Kenneth Ng, Ethereum Foundation",
      name: "Kenneth Ng",
      job: "Ethereum Foundation",
      disabled: false,
    },
    mariano: {
      title: "Learn about our Investor - Mariano Conti",
      href: "https://twitter.com/nanexcool",
      src: "mariano",
      alt: "Sketch of Investor - Mariano Conti",
      name: "Mariano Conti",
      job: "Awesome Guy",
      disabled: false,
    },
    scott: {
      title: "Learn about our Investor - Scott Moore, Co-Founder, Gitcoin",
      href: "https://twitter.com/notscottmoore",
      src: "scott",
      alt: "Sketch of Investor - Scott Moore, Co-Founder, Gitcoin",
      name: "Scott Moore",
      job: "Co-Founder, Gitcoin",
      disabled: false,
    },
    sandeep: {
      title: "Learn about our Investor - Sandeep Nailwal, Co-Founder, Polygon",
      href: "https://twitter.com/sandeepnailwal",
      src: "sandeep",
      alt: "Sketch of Investor - Sandeep Nailwal, Co-Founder, Polygon",
      name: "Sandeep Nailwal",
      job: "Co-Founder, Polygon",
      disabled: false,
    },
    defidad: {
      title: "Learn about our Investor - DeFiDad, COO, Zapper.Fi",
      href: "https://twitter.com/DeFi_Dad",
      src: "defidadinv",
      alt: "Sketch of Investor - DeFiDad, COO, Zapper.Fi",
      name: "DeFi Dad",
      job: "All Things DeFi",
      disabled: false,
    },
    anthony: {
      title: "Learn about our Investor - Anthony Sassano, EthHub",
      href: "https://twitter.com/sassal0x",
      src: "anthony",
      alt: "Sketch of Investor - Anthony Sassano, EthHub",
      name: "Anthony Sassano",
      job: "EthHub / DailyGWEI",
      disabled: false,
    },
    preethi: {
      title: "Learn about our Investor - Preethi Kasireddy, Entrepreneur",
      href: "https://twitter.com/iam_preethi",
      src: "preethi",
      alt: "Sketch of Investor - Preethi Kasireddy, Entrepreneur",
      name: "Preethi Kasireddy",
      job: "Writer / Entrepreneur",
      disabled: false,
    },
  },
  angelsoptional: {
    ravindra: {
      title: "Learn about our Investor - Ravindra Kumar, Founder, Frontier Wallet",
      href: "https://twitter.com/ravidsrk",
      src: "ravindra",
      alt: "Sketch of Investor - Ravindra Kumar, Founder, Frontier Wallet",
      name: "Ravindra Kumar",
      job: "Founder, Frontier Wallet",
      disabled: false,
    },
    ajit: {
      title: "Learn about our Investor - Ajit Tripathi, Head of Institional Business, AAVE",
      href: "ttps://twitter.com/chainyoda",
      src: "ajit",
      alt: "Sketch of Investor - Ajit Tripathi, Head of Institional Business, AAVE",
      name: "Ajit Tripathi",
      job: "AAVE",
      disabled: false,
    },
    luka: {
      title: "Learn about our Investor - Luka Sukik, Entreprenuer",
      href: "https://twitter.com/Beler",
      src: "lukasukik",
      alt: "Sketch of Investor - Luka Sukik, Entrepreneur",
      name: "Luka Sučić",
      job: "Entrepreneur",
      disabled: false,
    },
    rezo: {
      title: "Learn about our Investor - Rezo Shmertz, CEO, BR Capital",
      href: "https://br.capital/#team",
      src: "rezo",
      alt: "Sketch of Investor - Rezo, CEO, BR Capital",
      name: "Rezo Shmertz",
      job: "CEO, BR Capital",
      disabled: false,
    },
    evgeny: {
      title: "Learn about our Investor - Evgeny Zandman, Angel Investor",
      href: "https://br.capital/#team",
      src: "evgeny",
      alt: "Sketch of Investor - Evgeny Zandman, Angel Investor",
      name: "Evgeny Zandman",
      job: "Angel Investor",
      disabled: false,
    },
    ben: {
      title: "Sketch of Investor - Ben Lakoff, Entrepreneur",
      href: "https://twitter.com/benlakoff",
      src: "ben",
      alt: "Sketch of Investor - Ben Lakoff, Entrepreneur",
      name: "Ben Lakoff",
      job: "Entreprenuer",
      disabled: false,
    },
    auryn: {
      title: "Learn about our Investor - Auryn Macmillan, Gnosis",
      href: "https://twitter.com/auryn_macmillan",
      src: "auryn",
      alt: "Sketch of Investor - Auryn Macmillan, Gnosis",
      name: "Auryn Macmillan",
      job: "Gnosis",
      disabled: false,
    },
    kaito: {
      title: "Learn about our Investor - Kaito, Entrepreneur",
      href: "https://twitter.com/CoffeeTimesTW",
      src: "kaito",
      alt: "Sketch of Investor - Kaito, Coffee Times",
      name: "Kaito (Coffee Times)",
      job: "Founder, Webshake",
      disabled: false,
    },
    andrew: {
      title: "Learn about our Investor -  Andrew Chen, Entrepreneur",
      href: "https://www.linkedin.com/in/acschen/",
      src: "andrew",
      alt: "Sketch of Investor - Andrew Chen, Entrepreneur",
      name: "Andrew Chen",
      job: "Entrepreneur",
      disabled: false,
    },
    thomas: {
      title: "Learn about our Investor -  Thomas Kaseng AO, Angel Investor",
      href: "#",
      src: "thomas",
      alt: "Sketch of Investor - Thomas Kaseng AO, Angel Investor",
      name: "Thomas Kaseng AO",
      job: "Angel Investor",
      disabled: false,
    },
    karthik: {
      title: "Learn about our Investor -  Kartik Garg, Angel Investor",
      href: "#",
      src: "karthik",
      alt: "Sketch of Investor - Karthik Garg",
      name: "Kartik Garg",
      job: "Angel Investor",
      disabled: true,
    },
    ganeshram: {
      title: "Learn about our Investor -  Ganeshram Gunalan, Angel Investor",
      href: "https://twitter.com/ganeshram_g",
      src: "ganeshram",
      alt: "Sketch of Investor - Ganeshram Gunalan, Angel Investor",
      name: "Ganeshram Gunalan",
      job: "Angel Investor",
      disabled: false,
    },
  }
}

export default investorsList;
