const investorsList = {
  vcs: {
    true: {
      title: "Learn about our Investor - True Ventures",
      href: "https://trueventures.com/",
      src: "trueventures",
      alt: "Logo of True Ventures, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    binance: {
      title: "Learn about our Investor - Binance",
      href: "https://binance.com/",
      src: "binance",
      alt: "Logo of Binance, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    mysterio: {
      title: "Learn about our Investor - Mysterio",
      href: "#",
      src: "mysterio",
      alt: "Logo of Mysterio, Fund / Angel / Nothingness",
      name: false,
      job: false,
      disabled: true,
      hidden: false,
    },
    iosg: {
      title: "Learn about our Investor - iOSG",
      href: "https://iosg.vc/",
      src: "iosgventures",
      alt: "Logo of iOSG Ventures, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
    },
    thelao: {
      title: "Learn about our Investor - TheLAO",
      href: "https://www.thelao.io/",
      src: "thelao",
      alt: "Logo of The LAO, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    metacartel: {
      title: "Learn about our Investor - Meta Cartel",
      href: "https://www.metacartel.org/",
      src: "metacartel",
      alt: "Logo of Meta Cartel Ventures, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    ldcap: {
      title: "Learn about our Investor - LD Capital",
      href: "https://ldcap.com",
      src: "ldcapital",
      alt: "Logo of LD Capital, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    brcapital: {
      title: "Learn about our Investor - BR Capital",
      href: "https://br.capital/",
      src: "brcapital",
      alt: "Logo of BR Capital, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    bitscale: {
      title: "Learn about our Investor - Bitscale Capital",
      href: "https://bitscale.capital/",
      src: "bitscale",
      alt: "Logo of Bitscale Capital, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    bixin: {
      title: "Learn about our Investor - Bixin Ventures",
      href: "http://bixincapital.com/",
      src: "bixinventures",
      alt: "Logo of Bixin Ventures, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    fourthrev: {
      title: "Learn about our Investor - Fourth Revolution Capital",
      href: "https://fourthrevolution.capital/",
      src: "fourthrevolution",
      alt: "Logo of Fourth Revolution Capital, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    d64: {
      title: "Learn about our Investor - D64",
      href: "https://d64.vc/",
      src: "proofsystems_d64",
      alt: "Logo of D64, Crypto Fund",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    a_capital:{
      title: "Learn about our Investor - acapital",
      href: "https://acapital.com/",
      src: "acapital",
      alt: "Logo of Acapital", 
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    alphawave:{
      title: "Learn about our Investor - Alphawave",
      href: "https://www.awaveip.com/en/home/",
      src: "alphawave",
      alt: "Logo of Alphawave",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    coindcx:{
      title: "Learn about our Investor - Coindcx",
      href: "https://coindcx.com/",
      src: "coindcx",
      alt: "Logo of Coindcx",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    harmony:{
      title: "Learn about our Investor - Harmony",
      href: "https://www.harmony.one/",
      src: "harmony",
      alt: "Logo of Harmony",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    iseed:{
      title: "Learn about our Investor - Iseed",
      href: "#",
      src: "iseed",
      alt: "Logo of Iseed",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    parafi:{
      title: "Learn about our Investor - Parafi",
      href: "https://www.parafi.capital/",
      src: "parafi",
      alt: "Logo of Parafi",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    jumpcrypto:{
      title: "Learn about our Investor - Jumpcrypto",
      href: "https://jumpcrypto.com/",
      src: "jumpcrypto",
      alt: "Logo of Jumpcrypto",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    polygon:{
      title: "Learn about our Investor - Polygon",
      href: "https://polygon.technology/",
      src: "polygon",
      alt: "Logo of polygon",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    sinoglobal:{
      title: "Learn about our Investor - Sinoglobal",
      href: "https://www.sinoglobalcapital.com/",
      src: "sinoglobal",
      alt: "Logo of Sinoglobal",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    tigerglobal:{
      title: "Learn about our Investor - Tiger Global",
      href: "https://www.tigerglobal.com/",
      src: "tigerglobal",
      alt: "Logo of Tigerglobal",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    trgc:{
      title: "Learn about our Investor - Trgc",
      href: "https://trgc.io/",
      src: "trgc",
      alt: "Logo of Trgc",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    wintermute:{
      title: "Learn about our Investor - Wintermute",
      href: "https://www.wintermute.com/",
      src: "wintermute",
      alt: "Logo of wintermute",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    woodstock:{
      title: "Learn about our Investor - Woodstock",
      href: "#",
      src: "woodstock",
      alt: "Logo of Woodstock",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    zebpay:{
      title: "Learn about our Investor - Zebpay",
      href: "https://zebpay.com/",
      src: "zebpay",
      alt: "Logo of zebpay",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    },
    zeeprime:{
      title: "Learn about our Investor - Zeeprime",
      href: "https://zeeprime.capital/",
      src: "zeeprime",
      alt: "Logo of Zeeprime",
      name: false,
      job: false,
      disabled: false,
      hidden: false,
    }
  },
  angels: {
    balaji: {
      title: "Learn about our Investor - Balaji S. Srinivasan, Serial Entreprenuer",
      href: "https://balajis.com/",
      src: "balaji",
      alt: "Sketch of Investor - Balaji S. Srinivasan, Serial Entrepreneur",
      name: "Balaji S. Srinivasan",
      job: "Serial Entrepreneur",
      disabled: false,
      hidden: false,
    },
    ken: {
      title: "Learn about our Investor - Kenneth Ng, Ethereum Foundation",
      href: "https://twitter.com/nkennethk",
      src: "ken",
      alt: "Sketch of Investor - Kenneth Ng, Ethereum Foundation",
      name: "Kenneth Ng",
      job: "Ethereum Foundation",
      disabled: false,
      hidden: false,
    },
    mariano: {
      title: "Learn about our Investor - Mariano Conti",
      href: "https://twitter.com/nanexcool",
      src: "mariano",
      alt: "Sketch of Investor - Mariano Conti",
      name: "Mariano Conti",
      job: "Awesome Guy",
      disabled: false,
      hidden: false,
    },
    scott: {
      title: "Learn about our Investor - Scott Moore, Co-Founder, Gitcoin",
      href: "https://twitter.com/notscottmoore",
      src: "scott",
      alt: "Sketch of Investor - Scott Moore, Co-Founder, Gitcoin",
      name: "Scott Moore",
      job: "Co-Founder, Gitcoin",
      disabled: false,
      hidden: false,
    },
    sandeep: {
      title: "Learn about our Investor - Sandeep Nailwal, Co-Founder, Polygon",
      href: "https://twitter.com/sandeepnailwal",
      src: "sandeep",
      alt: "Sketch of Investor - Sandeep Nailwal, Co-Founder, Polygon",
      name: "Sandeep Nailwal",
      job: "Co-Founder, Polygon",
      disabled: false,
      hidden: false,
    },
    defidad: {
      title: "Learn about our Investor - DeFiDad, COO, Zapper.Fi",
      href: "https://twitter.com/DeFi_Dad",
      src: "defidadinv",
      alt: "Sketch of Investor - DeFiDad, COO, Zapper.Fi",
      name: "DeFi Dad",
      job: "All Things DeFi",
      disabled: false,
      hidden: false,
    },
    anthony: {
      title: "Learn about our Investor - Anthony Sassano, EthHub",
      href: "https://twitter.com/sassal0x",
      src: "anthony",
      alt: "Sketch of Investor - Anthony Sassano, EthHub",
      name: "Anthony Sassano",
      job: "EthHub / DailyGWEI",
      disabled: false,
      hidden: false,
    },
    preethi: {
      title: "Learn about our Investor - Preethi Kasireddy, Entrepreneur",
      href: "https://twitter.com/iam_preethi",
      src: "preethi",
      alt: "Sketch of Investor - Preethi Kasireddy, Entrepreneur",
      name: "Preethi Kasireddy",
      job: "Writer / Entrepreneur",
      disabled: false,
      hidden: false,
    },
    ajit:{
      title:"Learn about our Investor - Ajit",
      href: "#",
      src: "ajit",
      alt: "Sketch of Investor - Ajit",
      name: "Ajit",
      job: "",
      disabled: false,
      hidden: false,
    },
    andrewkeys:{
      title:"Learn about our Investor - Andrewkeys",
      href: "#",
      src: "andrewkeys",
      alt: "Sketch of Investor - Andrewkeys",
      name: "andrewkeys",
      job: "",
      disabled: false,
      hidden: false,
    },
    ankiet:{
      title:"Learn about our Investor - Aniket",
      href: "#",
      src: "aniket",
      alt: "Sketch of Investor - Aniket",
      name: "Aniket",
      job: "",
      disabled: false,
      hidden: false,
    },
    anton:{
      title:"Learn about our Investor - Anton",
      href: "#",
      src: "anton",
      alt: "Sketchf of Investor - Anton",
      name: "Anton",
      job: "",
      disabled: false,
      hidden: false,
    },
    david:{
      title:"Learn about our Investor - David",
      href: "#",
      src: "david",
      alt: "Sketchf of Investor - David",
      name: "David",
      job: "",
      disabled: false,
      hidden: false,
    },
    jerome:{
      title:"Learn about our Investor - Jerome",
      href: "#",
      src: "jerome",
      alt: "Sketchf of Investor - Jerome",
      name: "Jerome",
      job: "",
      disabled: false,
      hidden: false,
    },
    mateo:{
      title:"Learn about our Investor - Mateo",
      href: "#",
      src: "mateo",
      alt: "Sketchf of Investor - Mateo",
      name: "Mateo",
      job: "",
      disabled: false,
      hidden: false,
    },
    sahil:{
      title:"Learn about our Investor - Sahil",
      href: "#",
      src: "sahil",
      alt: "Sketchf of Investor - Sahil",
      name: "Sahil",
      job: "",
      disabled: false,
      hidden: false,
    },
    sam:{
      title:"Learn about our Investor - Sam",
      href: "#",
      src: "sam",
      alt: "Sketchf of Investor - Sam",
      name: "Sam",
      job: "",
      disabled: false,
      hidden: false,
    },
  },
  angelsoptional: {
    ravindra: {
      title: "Learn about our Investor - Ravindra Kumar, Founder, Frontier Wallet",
      href: "https://twitter.com/ravidsrk",
      src: "ravindra",
      alt: "Sketch of Investor - Ravindra Kumar, Founder, Frontier Wallet",
      name: "Ravindra Kumar",
      job: "Founder, Frontier Wallet",
      disabled: false,
      hidden: true,
    },
    ajit: {
      title: "Learn about our Investor - Ajit Tripathi, Head of Institional Business, AAVE",
      href: "ttps://twitter.com/chainyoda",
      src: "ajit",
      alt: "Sketch of Investor - Ajit Tripathi, Head of Institional Business, AAVE",
      name: "Ajit Tripathi",
      job: "AAVE",
      disabled: false,
      hidden: true,
    },
    luka: {
      title: "Learn about our Investor - Luka Sukik, Entreprenuer",
      href: "https://twitter.com/Beler",
      src: "lukasukik",
      alt: "Sketch of Investor - Luka Sukik, Entrepreneur",
      name: "Luka Sučić",
      job: "Entrepreneur",
      disabled: false,
      hidden: true,
    },
    rezo: {
      title: "Learn about our Investor - Rezo Shmertz, CEO, BR Capital",
      href: "https://br.capital/#team",
      src: "rezo",
      alt: "Sketch of Investor - Rezo, CEO, BR Capital",
      name: "Rezo Shmertz",
      job: "CEO, BR Capital",
      disabled: true,
      hidden: true,
    },
    evgeny: {
      title: "Learn about our Investor - Evgeny Zandman, Angel Investor",
      href: "https://br.capital/#team",
      src: "evgeny",
      alt: "Sketch of Investor - Evgeny Zandman, Angel Investor",
      name: "Evgeny Zandman",
      job: "Angel Investor",
      disabled: true,
      hidden: true,
    },
    ben: {
      title: "Sketch of Investor - Ben Lakoff, Entrepreneur",
      href: "https://twitter.com/benlakoff",
      src: "ben",
      alt: "Sketch of Investor - Ben Lakoff, Entrepreneur",
      name: "Ben Lakoff",
      job: "Entreprenuer",
      disabled: true,
      hidden: true,
    },
    auryn: {
      title: "Learn about our Investor - Auryn Macmillan, Gnosis",
      href: "https://twitter.com/auryn_macmillan",
      src: "auryn",
      alt: "Sketch of Investor - Auryn Macmillan, Gnosis",
      name: "Auryn Macmillan",
      job: "Gnosis",
      disabled: false,
      hidden: true,
    },
    kaito: {
      title: "Learn about our Investor - Kaito, Entrepreneur",
      href: "https://twitter.com/CoffeeTimesTW",
      src: "kaito",
      alt: "Sketch of Investor - Kaito, Coffee Times",
      name: "Kaito (Coffee Times)",
      job: "Founder, Webshake",
      disabled: false,
      hidden: true,
    },
    andrew: {
      title: "Learn about our Investor -  Andrew Chen, Entrepreneur",
      href: "https://www.linkedin.com/in/acschen/",
      src: "andrew",
      alt: "Sketch of Investor - Andrew Chen, Entrepreneur",
      name: "Andrew Chen",
      job: "Entrepreneur",
      disabled: false,
      hidden: true,
    },
    thomas: {
      title: "Learn about our Investor -  Thomas Kaseng AO, Angel Investor",
      href: "#",
      src: "thomas",
      alt: "Sketch of Investor - Thomas Kaseng AO, Angel Investor",
      name: "Thomas Kaseng AO",
      job: "Angel Investor",
      disabled: false,
      hidden: true,
    },
    karthik: {
      title: "Learn about our Investor -  Kartik Garg, Angel Investor",
      href: "#",
      src: "karthik",
      alt: "Sketch of Investor - Karthik Garg",
      name: "Kartik Garg",
      job: "Angel Investor",
      disabled: false,
      hidden: true,
    },
    ganeshram: {
      title: "Learn about our Investor -  Ganeshram Gunalan, Angel Investor",
      href: "https://twitter.com/ganeshram_g",
      src: "ganeshram",
      alt: "Sketch of Investor - Ganeshram Gunalan, Angel Investor",
      name: "Ganeshram Gunalan",
      job: "Angel Investor",
      disabled: false,
      hidden: true,
    },
  }
}

export default investorsList;
