
export  const pushDeligatees=[
    {
      name:"aiswarya",
      image:"/governance/aiswarya.jpg",
    },
    {
      name:"alex",
      image:"/governance/alex.jpg",
    },
    {
      name:"ashis",
      image:"/governance/ashis.jpg",
    },
    {
      name:"auryn",
      image:"/governance/auryn.jpg",
    },
    {
      name:"beler",
      image:"/governance/beler.jpg",
    },
    {
      name:"blake",
      image:"/governance/blake.jpg",
    },
    {
      name:"defi_dad",
      image:"/governance/defi_dad.jpg",
    },
    {
      name:"imvijaygir",
      image:"/governance/imvijaygir.jpg",
    },
    {
      name:"jaf",
      image:"/governance/jaf.jpg",
    },
    {
      name:"jude",
      image:"/governance/jude.jpg",
    },
    {
      name:"krishna",
      image:"/governance/krishna.jpg",
    },
    {
      name:"pranshu",
      image:"/governance/pranshu.jpg",
    },
    {
      name:"ray",
      image:"/governance/ray.jpg",
    },
    {
      name:"robin_rrtx",
      image:"/governance/robin_rrtx.jpg",
    },
    
   
    {
      name:"jude",
      image:"/governance/jude.jpg",
    },
  ]