/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Push | The Communication Protocol of Web3",
  "tagline": "One place to learn about everything Push Protocol!",
  "favicon": "/assets/website/favicon.ico",
  "url": "https://push.org",
  "baseUrl": "/",
  "trailingSlash": false,
  "organizationName": "ethereum-push-notification-service",
  "projectName": "push-website",
  "deploymentBranch": "gh-pages-d1",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "staticDirectories": [
    "public",
    "static"
  ],
  "presets": [
    [
      "classic",
      {
        "gtag": {
          "trackingID": "G-N9ZHXNRLYL"
        },
        "docs": {
          "path": "docs",
          "routeBasePath": "docs",
          "sidebarPath": "D:\\Push_Protocol\\push-website\\sidebars.js",
          "sidebarCollapsed": false,
          "editUrl": "https://github.com/ethereum-push-notification-service/push-documentation/"
        },
        "blog": {
          "showReadingTime": true,
          "path": "blog",
          "routeBasePath": "blog",
          "blogSidebarTitle": "All posts",
          "blogSidebarCount": "ALL"
        },
        "theme": {
          "customCss": "D:\\Push_Protocol\\push-website\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "scripts": [
    "./src/customscripts.js"
  ],
  "plugins": [
    "D:\\Push_Protocol\\push-website\\plugins\\custom-webpack-plugin\\index.js"
  ],
  "themeConfig": {
    "image": "/assets/docs/social-card.jpg",
    "themeconfig": {
      "sidebarCollapsible": false
    },
    "navbar": {
      "hideOnScroll": true,
      "logo": {
        "alt": "Push Logo",
        "src": "/assets/docs/PushLogoTextDark.svg",
        "srcDark": "/assets/docs/PushLogoTextWhite.svg"
      },
      "items": [
        {
          "to": "/docs/",
          "position": "right",
          "label": "Docs Hub"
        },
        {
          "to": "/blog",
          "label": "Blog",
          "position": "right"
        },
        {
          "to": "https://discord.com/invite/pushprotocol",
          "label": "Discord",
          "position": "right"
        },
        {
          "to": "https://app.push.org/",
          "label": "App",
          "position": "right"
        },
        {
          "href": "https://github.com/ethereum-push-notification-service/",
          "label": "GitHub",
          "position": "right"
        }
      ]
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "algolia": {
      "appId": "LHUKHXUHQP",
      "apiKey": "2fc69a715b81b57bcae4ad6edeb52abe",
      "indexName": "v2-push",
      "insights": true,
      "contextualSearch": true,
      "searchParameters": {},
      "searchPagePath": "search"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "customFields": {},
  "themes": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
